--liquibase formatted sql

--changeset hansvillaizan:create-table-attachment context:"dev, cert, prod"
CREATE TABLE ATTACHMENT (
    ATTACHMENT_ID INT IDENTITY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    URI VARCHAR(256) NOT NULL,
    STATUS BIT NOT NULL,
    UPDATE_USER VARCHAR(10)  NULL,
    CREATE_USER VARCHAR(10) NOT NULL,
    UPDATE_DATE DATETIME NULL,
    CREATE_DATE DATETIME NOT NULL,
    CONSTRAINT ATTACHMENTS_pk PRIMARY KEY (ATTACHMENT_ID)
)
GO

--rollback drop table [TESTREFACTOR].[ATTACHMENT]
